### ISSUE TITLE
모자이크 처리된 영상에 음성이 안들어가있음

### ISSUE THREAD

**Issue by Kim-yonguk** [kookmin-sw/2019-cap1-2019_11#3]
모자이크 처리된 영상에 음성이 안들어가있음

**Comment by dnap512** [comment]
https://zulko.github.io/moviepy/ref/ffmpeg.html?highlight=extract%20audio#moviepy.video.io.ffmpeg_tools.ffmpeg_extract_audio

moviepy 의 ffmpeg tool을 쓰면 오디오를 추출할수있고, 오디오와 비디오를 merge 할수도있음.
mpeg파일만 되는것으로 보임?

**Comment by dnap512** [comment]
https://github.com/senko/python-video-converter

video-converter 라는 모듈, 여러포맷 사용가능함

**Comment by dnap512** [comment]
https://github.com/kookmin-sw/2019-cap1-2019_11/tree/face_detection_and_recognition/yoloface/extract_audio_and_merge

mpeg 파일에서 오디오 추출후 다시 merge하는 코드 업로드
